# Generated by Django 5.0 on 2025-07-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"verbose_name": "Заявка", "verbose_name_plural": "Заявки"},
        ),
    ]
